### ISSUE TITLE
Support X-B3 (Zipkin) style http headers

### ISSUE THREAD

**Issue by mowknow** [ccadllc/cedi-dtrace#19]
There is no standard for http headers for distributed tracing, but the closest thing is [X-B3 style headers](https://github.com/openzipkin/b3-propagation) . These are used by several products, such as Zipkin, [http4s](https://http4s.org/v0.19/api/org/http4s/headers/index.html) or [istio](https://istio.io/docs/tasks/telemetry/distributed-tracing.html). It would be good if cedi-trace supported these, at least the three that are identical: trace-id, parent-id, span-id. This would give cedi-trace interoperability with other products.

Examples of money headers vs. x-b3 headers:

X-MoneyTrace: trace-id=de305d54-75b4-431b-adb2-eb6b9e546013;parent-id=3285573610483682037;span-id=3285573610483682037

X-B3-TraceId: 463ac35c9f6413ad48485a3953bb6124
X-B3-ParentSpanId: 0020000000000001
X-B3-SpanId: a2fb4a1d1a96d312

**Comment by sbuzzard** [comment]
We don't really have much http support in cedi-dtrace proper, since the insertion of such headers are highly specific to the http library you're using.  Though I could see adding a dtrace-http4s or dtrace-akka-http module.  At comcast in our internal thunderbird library's nio module, we provide convenience functions to do insertion for akka-http, for instance..  Currently the only "support" of http headers in cedi-dtrace proper is a single value on Span called toHeader, which is a simple interpolated string.  It's always bothered me that it was there since it doesn't really belong in dtrace-core but at the time I was trying to centralize it since I was using this header not only for http but also to embed in a remotely rpc header.   But agree that if we include any header information in core, it should probably be b3.

**Comment by mpilquist** [comment]
Closed by #20.
